import { parseConfig } from "./schema";
import type { FlagConfig, JsonValue } from "./types";

export interface GenerateTypesOptions {
  interfaceName?: string;
  banner?: string;
}

function literal(value: JsonValue): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value))
    return `readonly [${value.map(literal).join(", ")}]`;
  return `{ readonly ${Object.entries(value)
    .map(([key, entry]) => `${JSON.stringify(key)}: ${literal(entry)}`)
    .join("; ")} }`;
}

/** Generates zero-runtime-cost flag value and variation maps from a validated config. */
export function generateTypes(
  config: FlagConfig,
  options: GenerateTypesOptions = {},
): string {
  const parsed = parseConfig(config);
  const name = options.interfaceName ?? "SuperflagFlagValues";
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name))
    throw new TypeError("interfaceName must be a TypeScript identifier");
  const values = Object.entries(parsed.flags).map(([flagKey, flag]) => {
    const types = [
      ...new Set(
        Object.values(flag.variations).map((variation) =>
          literal(variation.value),
        ),
      ),
    ];
    return `  ${JSON.stringify(flagKey)}: ${types.join(" | ")};`;
  });
  const variations = Object.entries(parsed.flags).map(
    ([flagKey, flag]) =>
      `  ${JSON.stringify(flagKey)}: ${Object.keys(flag.variations)
        .map((variation) => JSON.stringify(variation))
        .join(" | ")};`,
  );
  const definitions = Object.entries(parsed.flags).map(
    ([flagKey, flag]) =>
      `  ${JSON.stringify(flagKey)}: { readonly type: ${JSON.stringify(flag.type)}; readonly description: ${JSON.stringify(flag.description)}; readonly tags: readonly [${flag.tags.map((tag) => JSON.stringify(tag)).join(", ")}]; readonly owner: ${JSON.stringify(flag.owner)}; readonly lifecycle: ${JSON.stringify(flag.lifecycle)} };`,
  );
  return `${options.banner ?? "// Generated by @superflag-sh/core. Do not edit."}\n\nexport type SuperflagConfigVersion = ${parsed.configVersion};\nexport type SuperflagSource = { readonly app: ${JSON.stringify(parsed.source.app)}; readonly environment: ${JSON.stringify(parsed.source.environment)} };\n\nexport interface ${name} {\n${values.join("\n")}\n}\n\nexport interface SuperflagVariationIds {\n${variations.join("\n")}\n}\n\nexport interface SuperflagFlagDefinitions {\n${definitions.join("\n")}\n}\n\nexport type SuperflagFlagKey = keyof ${name};\n`;
}
